### ISSUE TITLE
NetID Login not working - High

### ISSUE THREAD

**Issue by asmart3** [esolache/TBR#13]
Logging in with NetID is not currently functional. At this point, it is going to be difficult to gain access to NetID credentials, so I would suggest making a separate account creation system in your local server. Otherwise, the only way people can log in is through dummy data that is not unique to their actual person.

Severity: High

**Comment by emwinckler** [comment]
Avoiding allowing letting users to create accounts because this would be done by the UW system.  Admin privileges are restricted to general users and will be done via web based version already in place.
