### ISSUE TITLE
Determining Students and Tutors - High

### ISSUE THREAD

**Issue by asmart3** [esolache/TBR#17]
There's currently no function for turning a student into a tutor or vice versa, or becoming both a student and a tutor. This seems to be another problem that could be fixed in account creation where accounts can pick whether they're a student, tutor, or both. However, if this group still wants to press on with NetID login, I would suggest making all accounts student/tutor combos.

Severity: High

**Comment by emwinckler** [comment]
These are privileges reserved for admin accounts which will operate via the web based version.  Closing this issue because we want to avoid users creating accounts and setting privileges.
