### ISSUE TITLE
Buggy Scrolling in most screens - Low

### ISSUE THREAD

**Issue by asmart3** [esolache/TBR#8]
Description: In multiple screens, the scrolling seems to be very fidgety. Some examples include the calendar in the 'Change Availability' screen. When scrolling down, it jumps straight to the bottom and skips the times from 12 pm to 3 pm, and then when I try scrolling up again, it jumps straight to the top. The same issue happens in the 'Change Courses' screen for the Add/Remove classes lists.

Severity: Low

**Comment by emwinckler** [comment]
Can't recreate.  Presuming this is limited in scope and could be an issue of running the emulator on your current system.
